---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  - autoconf
  - bash-completion
  - gettext
  - gifsicle
  - git
  - go
  - gpg
  - hub
  - httpie
  - libevent
  - mcrypt
  - nmap
  - node
  - nvm
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - wget
  - wrk # better than AB?
  - zsh
  - tmux
  - dockutil
  # Elixir Development
  - erlang
  - elixir
  - ruby
  - postgres
  # General Development
  - awscli
  - cf-cli
  # Other
  - osquery

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - cloudfoundry/tap

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - docker
  - google-chrome
  - licecap
  - macvim
  - sequel-pro
  - skitch
  - cyberduck
  - atom
  - alfred
  - tunnelblick
  - spectacle
  - postgres
  - gpg-suite
  - omnifocus
  - slack
  - dashlane
  # - blue-jeans
  - iterm2
  # - blender
  - dropbox
  - iterative/homebrew-dvc/dvc

# Atom configuration
atom_upgrade_all: True
atom_packages:
  - aligner
  - aligner-ruby
  - color-picker
  - compare-files
  - gist
  - linter
  - linter-ruby
  - linter-swagger
  - linter-rubocop
  - atom-beautify
  - minimap-linter
  - pretty-json
  - rails-i18n-autocomplete
  - sequence-diagram
  - markdown-table-editor
  - markdown-table-formatter
  - merge-conflicts
  - imdone-atom-github
  - sort-lines
  - trailing-spaces
  - minimap
  - ruby-test
  - busy-signal
  - column-select
  - git-blame
  # Language Support
  - language-ansible
  - language-babel
  - language-puppet
  - language-rspec
  - language-babel
  - language-java
  - language-ruby
  - language-python
  - language-docker

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Dockutil
dockitems_to_remove:
  - Launchpad
  - Mail
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - System Preferences
  - Calendar
  - Numbers
  - Pages
  - Keynote
  - News
  - Siri

dockitems_to_persist:
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 1
  - name: Atom
    path: /Applications/Atom.app
    pos: 2

# Install path for rvm (defaults to single user)
# NOTE: If you are doing a ROOT BASED INSTALL then make sure you
#       set the install path to something like '/usr/local/rvm'
rvm1_install_path: '~/.rvm' # '/usr/local/rvm' # '~/.rvm'
rvm1_bundler_install: True
rvm1_user: matt
rvm1_rubies:
  - 'ruby-2.5'

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
gem_packages:  []
npm_packages: []
pip_packages: # []
  - name: speedtest-cli
    state: present
    extra_args: --user

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
